name: notes_app_flutter
description: A Flutter app for creating, editing and searching notes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
